import { LanguageOption } from "@/types";

export const ttsLanguageOptions: LanguageOption[] = [
  // { name: "Afrikaans", locale: "af-ZA" },
  // { name: "Amharic", locale: "am-ET" },
  // { name: "Arabic (Egypt)", locale: "ar-EG" },
  { name: "Arabic (Saudi Arabia)", locale: "ar-SA" },
  // { name: "Azerbaijani", locale: "az-AZ" },
  // { name: "Bulgarian", locale: "bg-BG" },
  // { name: "Bengali (Bangladesh)", locale: "bn-BD" },
  { name: "Bengali (India)", locale: "bn-IN" },
  // { name: "Bosnian", locale: "bs-BA" },
  // { name: "Catalan", locale: "ca-ES" },
  { name: "Czech", locale: "cs-CZ" },
  // { name: "Welsh", locale: "cy-GB" },
  { name: "Danish", locale: "da-DK" },
  // { name: "German (Austria)", locale: "de-AT" },
  // { name: "German (Switzerland)", locale: "de-CH" },
  { name: "German", locale: "de-DE" },
  { name: "Greek", locale: "el-GR" },
  // { name: "English (Australia)", locale: "en-AU" },
  // { name: "English (Canada)", locale: "en-CA" },
  // { name: "English (United Kingdom)", locale: "en-GB" },
  // { name: "English (Ireland)", locale: "en-IE" },
  // { name: "English (India)", locale: "en-IN" },
  { name: "English (United States)", locale: "en-US" },
  { name: "Spanish (Spain)", locale: "es-ES" },
  { name: "Spanish (Mexico)", locale: "es-MX" },
  // { name: "Estonian", locale: "et-EE" },
  // { name: "Basque", locale: "eu-ES" },
  { name: "Persian", locale: "fa-IR" },
  { name: "Finnish", locale: "fi-FI" },
  // { name: "Filipino", locale: "fil-PH" },
  // { name: "French (Belgium)", locale: "fr-BE" },
  // { name: "French (Canada)", locale: "fr-CA" },
  // { name: "French (Switzerland)", locale: "fr-CH" },
  { name: "French", locale: "fr-FR" },
  // { name: "Irish", locale: "ga-IE" },
  // { name: "Galician", locale: "gl-ES" },
  { name: "Hebrew", locale: "he-IL" },
  { name: "Hindi", locale: "hi-IN" },
  // { name: "Croatian", locale: "hr-HR" },
  // { name: "Hungarian", locale: "hu-HU" },
  // { name: "Armenian", locale: "hy-AM" },
  // { name: "Indonesian", locale: "id-ID" },
  // { name: "Icelandic", locale: "is-IS" },
  { name: "Italian", locale: "it-IT" },
  { name: "Japanese", locale: "ja-JP" },
  // { name: "Javanese", locale: "jv-ID" },
  // { name: "Georgian", locale: "ka-GE" },
  // { name: "Kazakh", locale: "kk-KZ" },
  // { name: "Khmer", locale: "km-KH" },
  // { name: "Kannada", locale: "kn-IN" },
  { name: "Korean", locale: "ko-KR" },
  // { name: "Lao", locale: "lo-LA" },
  // { name: "Lithuanian", locale: "lt-LT" },
  // { name: "Latvian", locale: "lv-LV" },
  // { name: "Macedonian", locale: "mk-MK" },
  // { name: "Malayalam", locale: "ml-IN" },
  // { name: "Mongolian", locale: "mn-MN" },
  // { name: "Malay", locale: "ms-MY" },
  // { name: "Maltese", locale: "mt-MT" },
  // { name: "Burmese", locale: "my-MM" },
  { name: "Norwegian Bokmål", locale: "nb-NO" },
  { name: "Nepali", locale: "ne-NP" },
  // { name: "Dutch (Belgium)", locale: "nl-BE" },
  { name: "Dutch", locale: "nl-NL" },
  { name: "Polish", locale: "pl-PL" },
  { name: "Pashto", locale: "ps-AF" },
  { name: "Portuguese (Brazil)", locale: "pt-BR" },
  { name: "Portuguese", locale: "pt-PT" },
  // { name: "Romanian", locale: "ro-RO" },
  { name: "Russian", locale: "ru-RU" },
  // { name: "Sinhala", locale: "si-LK" },
  // { name: "Slovak", locale: "sk-SK" },
  // { name: "Slovenian", locale: "sl-SI" },
  { name: "Somali", locale: "so-SO" },
  // { name: "Albanian", locale: "sq-AL" },
  // { name: "Serbian", locale: "sr-RS" },
  // { name: "Sundanese", locale: "su-ID" },
  { name: "Swedish", locale: "sv-SE" },
  { name: "Swahili", locale: "sw-KE" },
  // { name: "Tamil", locale: "ta-IN" },
  // { name: "Telugu", locale: "te-IN" },
  { name: "Thai", locale: "th-TH" },
  { name: "Turkish", locale: "tr-TR" },
  { name: "Ukrainian", locale: "uk-UA" },
  { name: "Urdu", locale: "ur-PK" },
  // { name: "Uzbek", locale: "uz-UZ" },
  { name: "Vietnamese", locale: "vi-VN" },
  { name: "Chinese (Simplified)", locale: "zh-CN" },
  // { name: "Chinese (Hong Kong)", locale: "zh-HK" },
  // { name: "Chinese (Traditional)", locale: "zh-TW" },
  // { name: "Zulu", locale: "zu-ZA" },
].toSorted((a, b) => a.name.localeCompare(b.name));

